# Generated by Django 3.2.9 on 2022-05-23 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo_item',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
