# Generated by Django 3.2.9 on 2022-05-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_v1', '0002_auto_20220523_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_item',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='todo_item',
            name='finished_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo_item',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
